more improvements

diff --git a/.github/actions/load-latest-image/action.yaml b/.github/actions/load-latest-image/action.yaml
--- a/.github/actions/load-latest-image/action.yaml
+++ b/.github/actions/load-latest-image/action.yaml
@@ -32,18 +32,18 @@ runs:
         podman --root /var/lib/shared pull -q ${{ env.IMAGE_FULL }}:latest || true
         podman --root /var/lib/shared pull -q ghcr.io/${{ github.repository }}/homeserver-centos-bootc:latest || true
         podman image prune -f # cleanup dangling images
+        podman --root /var/lib/shared image prune -f || true # cleanup dangling images
         sudo chmod -R a+rx /var/lib/shared # podman bug workaround
 
     - name: start local registry
       shell: bash
       if: ${{ runner.environment  == 'self-hosted' }}
       run: | #sh
-
         # Start a local registry
         podman pull -q docker.io/library/registry:2
         podman run -d --name local-registry \
           -p 5000:5000 \
-          -v /var/lib/registry:/var/lib/registry \
+          -v /var/lib/registry/${{ github.run_id }}:/var/lib/registry \
           docker.io/library/registry:2
 
     - name: Move from root storage to rootless storage through local registry
@@ -57,10 +57,11 @@ runs:
         podman push --tls-verify=false --quiet 127.0.0.1:5000/homeserver-centos-bootc:latest
 
         echo "podman images before transfer:"
+        podman image prune -f
         podman images
 
-        podman pull --tls-verify=false 127.0.0.1:5000/${{ env.IMAGE_NAME }}:latest
-        podman pull --tls-verify=false 127.0.0.1:5000/homeserver-centos-bootc:latest
+        podman pull --tls-verify=false --quiet 127.0.0.1:5000/${{ env.IMAGE_NAME }}:latest
+        podman pull --tls-verify=false --quiet 127.0.0.1:5000/homeserver-centos-bootc:latest
 
         podman tag 127.0.0.1:5000/${{ env.IMAGE_NAME }}:latest ${{ env.IMAGE_FULL }}:latest
         podman tag 127.0.0.1:5000/homeserver-centos-bootc:latest ghcr.io/${{ github.repository }}/homeserver-centos-bootc:latest
